"""add new columns

Revision ID: 94253f75dd9d
Revises: 6cc3062519ac
Create Date: 2019-03-18 15:04:29.033321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94253f75dd9d'
down_revision = '6cc3062519ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
